[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "unifeed"
authors = [{name = "Team 4D2", email = "team4d2@unifeed"}]
dynamic = ["version", "description"]
